import { CITIES, CONTRACTS, ROADS } from '../../models/worldTour/worldAdventure.js';
import { ACTIVE_UNIT } from '../../models/worldTour/worldPolice.js';
import { ExperienceDialog } from '../shared/ExperienceDialog.jsx';
// Connection chip: who else is here, and whether this is the shared online world or the same-browser fallback.
function onlineLabel({ status, peers }) {
  const others = peers.length, players = `${others} other player${others === 1 ? '' : 's'} here`;
  if (status.state === 'error') return ['offline', 'Offline · playing solo'];
  if (status.mode === 'local') return ['local', `Local · ${others} other tab${others === 1 ? '' : 's'}`];
  if (status.state !== 'online') return ['connecting', 'Connecting to the shared world…'];
  return ['online', `Online · ${players}`];
}
export default function WorldView({ controller, onEditCharacter }) {
  const { online, playerName, hud, panel, ready, error, storage, host, city, current, p, point, open, action, toggleBlood, touchControl, travel, dispatchTitle, dispatchHint, task, blood, acceptContract, abandonContract, recoverToSafehouse } = controller;
  return <div className="adventure" style={{ '--city-accent': city.color }}>
    <div className="adventure-canvas" ref={host} />
    <header className="adventure-header"><a href="#world" onClick={e => { e.preventDefault(); open('world'); }} className="adventure-brand">lc<span>WORLD TOUR</span><i>✦</i></a><nav aria-label="World navigation"><button onClick={() => open('world')}>◎ <span>World map</span><kbd>M</kbd></button><button onClick={() => open('contracts')}>◇ <span>Contracts</span><kbd>L</kbd></button><button onClick={() => open('help')} aria-label="Controls and pause menu">Ⅱ</button></nav></header>
    <section className="adventure-location"><span className="adventure-kicker">{city.country} / {city.region}</span><h1>{city.name}<span>.</span></h1><div><i />{city.district}<span>FREE ROAM</span></div>{(() => { const [state, text] = onlineLabel(online); return <p className={'adventure-online ' + state} role="status" aria-live="polite">{text}</p>; })()}</section>
    <section className="adventure-stats" aria-label="Player status"><span className="adventure-player">{playerName.toUpperCase()}</span><div className="wanted" aria-label={`Wanted level ${Math.ceil(hud.heat)}`}><span className={hud.heat >= 0.01 ? 'lit' : ''}>★</span><span className={hud.heat > 1 ? 'lit' : ''}>★</span><span className={hud.heat > 2 ? 'lit' : ''}>★</span></div><strong>${hud.cash.toLocaleString()}</strong><label><span>HEALTH</span><b>{Math.ceil(hud.health)}</b><progress max="100" value={hud.health} /></label><div className="weapon-status"><span>{hud.driving ? 'SPORT COUPE' : hud.weapon === 'pistol' ? 'PISTOL' : 'UNARMED'}</span><b>{hud.driving ? `${Math.round(Math.abs(hud.car.speed) * 3.6)} km/h` : hud.reload > 0 ? 'RELOADING' : hud.weapon === 'pistol' ? `${hud.ammo} / ∞` : 'FISTS'}</b></div></section>
    <section className="adventure-objective"><div className="adventure-kicker">{current ? current.type + ' / ACTIVE CONTRACT' : 'YOUR NEXT MOVE'}</div><h2>{task}</h2><p>{current ? `${current.title} · $${current.reward.toLocaleString()}` : 'Seven cities. No set route. Make your next move.'}</p>{point && <span className="objective-distance">◇ {Math.round(Math.hypot(p.x - point.x, p.z - point.z))} m <small>Follow the gold marker · E to interact</small></span>}<button onClick={() => open('contracts')}>{current ? 'Contract details' : 'Find a contract'} <span>↗</span></button></section>
    {hud.heat > 0 && <div className="adventure-dispatch" aria-label="Police response"><span>POLICE RESPONSE</span><strong>{dispatchTitle}</strong><small>{dispatchHint}</small></div>}
    {hud.messageTime > 0 && <div className="adventure-toast" role="status">{hud.message}</div>}
    {hud.down > 0 && <div className={'adventure-wasted' + (hud.downReason === 'busted' ? ' busted' : '')}><h2>{hud.downReason === 'busted' ? 'BUSTED' : 'WASTED'}</h2><p>{hud.downReason === 'busted' ? 'Released at your safehouse…' : 'Returning to your safehouse…'}</p></div>}
    {!ready && !error && <div className="adventure-loading">Building your city…</div>}
    {error && <div className="adventure-loading"><strong>The city needs WebGL.</strong><p>Enable hardware acceleration and reload to play.</p><button onClick={() => location.reload()}>Reload</button></div>}
    <div className="adventure-bottom"><section className="adventure-radar" aria-label="City minimap"><div><span>↑ N</span><b>{city.district.toUpperCase()}</b></div><svg viewBox="-460 -460 920 920" role="img" aria-label="Streets, your position, car and mission destination"><rect x="-460" y="-460" width="920" height="920" fill="#182b31" />{hud.blocks.map((b, i) => <rect key={i} x={b.x - b.width / 2} y={b.z - b.depth / 2} width={b.width} height={b.depth} fill="#425453" />)}{ROADS.map(n => <g key={n} stroke="#82908a" strokeWidth="9"><path d={`M${n} -440V440`} /><path d={`M-440 ${n}H440`} /></g>)}<rect x="445" y="-460" width="15" height="920" fill="#609ba3" /><circle cx="8" cy="12" r="18" fill="#87c7a1" /><circle cx={hud.car.x} cy={hud.car.z} r="15" fill="#64ddd1" />{hud.heat > 0 && hud.unseen > 4 && hud.lastSeen && <circle cx={hud.lastSeen.x} cy={hud.lastSeen.z} r="70" fill="#88aaff1c" stroke="#88aaff70" strokeWidth="4" strokeDasharray="10 8" />}{hud.policeCars.map(c => <rect key={c.id} x={c.x - 12} y={c.z - 12} width="24" height="24" rx="5" fill={ACTIVE_UNIT.includes(c.state) ? (Math.floor(hud.time * 4) % 2 ? '#ff6d82' : '#6d9dff') : '#5d7597'} />)}{online.peers.map(peer => <circle key={peer.id} className="remote-player" cx={peer.x} cy={peer.z} r="15" fill="#f8f1a8" stroke="#152b32" strokeWidth="5"><title>{peer.name}</title></circle>)}{hud.enemies.filter(e => e.health > 0).map(e => <circle key={e.id} cx={e.x} cy={e.z} r="13" fill={e.kind === 'police' ? '#88aaff' : '#ff6d82'} />)}{point && <g><path d={`M${p.x} ${p.z}L${point.x} ${point.z}`} stroke="#f8d47a" strokeWidth="4" strokeDasharray="12 10" /><circle cx={point.x} cy={point.z} r="23" fill="#f8d47a" /></g>}<path d="M0 -24L17 18L0 11L-17 18Z" fill="white" stroke="#152b32" strokeWidth="5" transform={`translate(${p.x} ${p.z}) rotate(${180 - p.heading * 180 / Math.PI})`} /></svg><footer><span><i /> {hud.driving ? 'IN VEHICLE' : 'ON FOOT'}</span><button onClick={() => open('world')}>Expand ↗</button></footer></section><div className="adventure-hints"><span><kbd>W A S D</kbd> {hud.driving ? 'Drive' : 'Move'}</span><span><kbd>F</kbd> {hud.driving ? 'Exit car' : 'Enter car'}</span><span><kbd>J</kbd> Attack</span><span><kbd>E</kbd> Interact</span><small>Drag to look · Scroll to zoom</small></div><div className="adventure-actions"><button disabled={!ready || error} onClick={() => action('vehicle')}>{hud.driving ? 'Exit car' : 'Enter car'} <kbd>F</kbd></button><button disabled={!ready || error || hud.driving} {...touchControl('attack')}>Attack <kbd>J</kbd></button><button disabled={!ready || error} onClick={() => action('interact')}>Interact <kbd>E</kbd></button><button onClick={() => action('weapon')}>{hud.weapon === 'pistol' ? 'Use fists' : 'Use pistol'} <kbd>Q</kbd></button><button onClick={() => action('reload')}>Reload <kbd>R</kbd></button></div></div>
    <div className="adventure-touch" aria-label="Touch movement controls">{[['forward', '↑'], ['left', '←'], ['backward', '↓'], ['right', '→'], ['run', 'Run'], ['brake', hud.driving ? 'Brake' : 'Jump']].map(([key, title]) => <button key={key} className={'control-' + key} aria-label={key} {...touchControl(key)}>{title}</button>)}</div>
    {panel === 'world' && <ExperienceDialog title="One world. Your next chapter." className="adventure-dialog world-dialog" onClose={() => open(null)}><p>Travel between seven open districts. Every city has its own skyline, streets, and three contracts.</p><div className="atlas"><svg viewBox="0 0 1000 440" aria-label="World travel map"><defs><pattern id="atlas-grid" width="50" height="44" patternUnits="userSpaceOnUse"><path d="M50 0H0V44" fill="none" stroke="#ffffff0b" /></pattern></defs><rect width="1000" height="440" fill="url(#atlas-grid)" /><g fill="#354b52" stroke="#6c8184" strokeWidth="1"><path d="M75 75L150 35 275 65 300 105 255 145 245 195 215 220 185 170 135 140Z" /><path d="M270 210L350 225 385 270 350 325 305 400 295 310 265 260Z" /><path d="M435 83L485 58 535 73 555 130 495 149 445 127Z" /><path d="M450 152L532 143 587 210 551 280 510 367 477 302 451 230 425 189Z" /><path d="M543 64L677 40 800 60 930 110 862 171 821 222 765 210 723 155 674 192 629 145 565 140Z" /><path d="M786 307L866 285 927 335 887 371 804 365Z" /><path d="M329 40L379 32 395 75 356 100Z" /></g>{CITIES.map(c => <g key={c.id} transform={`translate(${c.map[0] * 10} ${c.map[1] * 4.4})`}><circle r={c.id === city.id ? 12 : 7} fill={c.color} opacity=".3" /><circle r="4" fill={c.color} /><text x="10" y="-10" fill="#f3ece1" fontSize="13">{c.name}</text></g>)}</svg></div>{(hud.mission || hud.heat > 0 || hud.down > 0) && <p className="travel-notice">Finish or abandon your contract and lose the police before flying.</p>}<div className="destination-grid">{CITIES.map(c => <button key={c.id} className={city.id === c.id ? 'selected' : ''} disabled={city.id === c.id || !!hud.mission || hud.heat > 0 || hud.down > 0 || !ready || error} onClick={() => travel(c.id)} style={{ '--destination-color': c.color }}><small>{c.country}</small><strong>{c.name}<span>{city.id === c.id ? '●' : '↗'}</span></strong><span>{c.district} · {hud.completed.filter(k => k.startsWith(c.id + ':')).length}/3 contracts{online.counts[c.id] ? ` · ${online.counts[c.id]} online` : ''}</span></button>)}</div><small>Stylized city districts connected by instant flights, not a real-scale Earth simulation.</small></ExperienceDialog>}
    {panel === 'contracts' && <ExperienceDialog title="Good work. Better pay." className="adventure-dialog" onClose={() => open(null)}><p>Available in {city.name}. Follow the gold marker, stop, then press E at the objective. Combat locks onto the nearest visible enemy in range.</p><div className="world-contracts">{CONTRACTS.map(m => { const done = hud.completed.includes(`${city.id}:${m.id}`); return <article key={m.id}><div><small>{m.type}</small><b>${m.reward.toLocaleString()}</b></div><h3>{m.title}</h3><p>{m.description}</p><button disabled={done || !!hud.mission || !ready || error || hud.down > 0} onClick={() => acceptContract(m.id)}>{done ? '✓ Completed' : hud.mission?.id === m.id ? 'In progress' : 'Accept contract ↗'}</button></article>; })}</div>{hud.mission && <button className="adventure-secondary" onClick={abandonContract}>Abandon current contract</button>}<p className="adventure-save">{storage ? 'Cash and completed contracts save automatically on this browser. Unfinished contracts restart after reloading.' : 'Browser storage is unavailable. Progress lasts for this session.'} {hud.completed.length}/21 completed.</p></ExperienceDialog>}
    {panel === 'help' && <ExperienceDialog title="Make yourself at home." className="adventure-dialog" onClose={() => open(null)}><p>The game is paused. Explore on foot or take your cyan coupe. Pick up contracts and fly to another country using the world map.</p><div className="adventure-help">{[['WASD / arrows', 'Move or drive'], ['Shift / Space', 'Sprint / jump; Space is the handbrake while driving'], ['F', 'Enter or exit your car (stop first)'], ['J / Attack', 'Shoot or punch; the ring shows who you will hit. Hold to keep firing'], ['Q / R', 'Switch fists / pistol; reload (automatic when empty)'], ['E', 'Collect, deliver, or heal at the green safehouse'], ['M / L', 'World map / contracts'], ['Drag / scroll', 'Look around / zoom']].map(([key, text]) => <div key={key}><kbd>{key}</kbd><span>{text}</span></div>)}</div><p>Shots and attacks attract police. Patrol cars respond by road and chase you while they can see you; out of sight, they search your last known location. At one star, officers try to arrest you on foot: stand still and you are busted and fined. Hurting bystanders or officers raises your stars, and at two or more officers open fire. Stop attacking for 12 seconds and stay out of police sight for 8 seconds to begin losing heat. Aim with the camera: the pistol locks onto threats first and only onto bystanders in front of you. Punches chain into a three-hit combo whose last hook knocks people down. Children are never targets. At zero health you respawn and can restart your contract. Return to the green safehouse and press E on foot to heal. Other players in your city appear with their own look and name tag (and in their car while driving) and on the minimap. Traffic, pedestrians, police and contracts are your own; you cannot collide with or fight other players.</p><div className="adventure-menu-actions"><button onClick={() => open(null)}>Resume game ↗</button><button aria-pressed={blood} onClick={toggleBlood}>Blood effects: {blood ? 'On' : 'Off'}</button><button onClick={recoverToSafehouse}>Recover to safehouse</button><button onClick={() => { open(null); onEditCharacter?.(); }}>Edit character</button></div></ExperienceDialog>}
  </div>;
}
